### PR TITLE
Updated daterangepicker to version 2.1.12

### PR DESCRIPTION
**Pull request by Sylvain**
Hi!

I just updated the lib to the last version.

Sylvain

### CODE REVIEW

**Comment by jordanbrock** [comment]
Thanks @Sylvain. Merged :+1:

**Comment by Sylvain** [comment]
:+1: for merging it! Is possible to publish a new gem version?

**Comment by jordanbrock** [comment]
@Sylvain Built and pushed to rubygems :)

**Comment by Sylvain** [comment]
:tada: Thanks!

**Pull request merged**
