### PR TITLE
replaces scss with rendered css

### PR DESCRIPTION
**Pull request by dimanyc**
tested this locally. My app's datepicker works as expected. Used an SCSS to CSS parser from [SassMeister](http://www.sassmeister.com/).

### CODE REVIEW

**Comment by olegykz** [comment]
Yep, it looks like it was scss file with css extension. But why you decide to remove source scss file?
Scss should be compiled to css according to assets pipeline process. Maybe just rename the file to correct extension?

**Comment by dimanyc** [comment]
I figured that it would be the best solution since SCSS is not listed as a dependency.

**Comment by jordanbrock** [comment]
I would prefer to leave it as scss and add sass-rails as a dependency. It would reduce the complexity of maintaining the project, and reduce the possibility of versions getting out of whack.

**Comment by dimanyc** [comment]
make sense

**Pull request closed without merging**
